---

## 3. Updated `SCHEMA.sql`

```sql
-- Create Custom Enum Types
CREATE TYPE member_status AS ENUM ('Prospect', 'Active', 'Inactive', 'Alumni');
CREATE TYPE prospect_stage AS ENUM ('1st Visit', '2nd Visit', 'Form Sent', 'Payment Pending', 'Onboarded');
CREATE TYPE attendance_status AS ENUM ('Present', 'Absent', 'Excused', 'Guest');

-- 1. Members Table
CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    phone TEXT,
    status member_status DEFAULT 'Prospect',
    pathway_level TEXT DEFAULT 'Level 1',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Prospect Pipeline Table
CREATE TABLE prospect_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT REFERENCES members(id) ON DELETE CASCADE,
    stage prospect_stage DEFAULT '1st Visit',
    last_contacted TIMESTAMPTZ DEFAULT NOW(),
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Meetings Table
CREATE TABLE meetings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_number INT UNIQUE NOT NULL,
    meeting_date DATE NOT NULL,
    theme TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Role Catalog Table
CREATE TABLE role_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name TEXT UNIQUE NOT NULL,
    category TEXT -- 'Executive', 'Major', or 'Functional'
);

-- Insert Default Club Roles
INSERT INTO role_catalog (role_name, category) VALUES
('Meeting Host', 'Major'),
('Topics Master', 'Major'),
('General Evaluator', 'Major'),
('Speech Evaluator', 'Major'),
('Speaker', 'Major'),
('Timer', 'Functional'),
('Filler Word Counter', 'Functional'),
('Language Evaluator', 'Functional'),
('Topics Evaluator', 'Functional');

-- 5. Role Assignments Table (Allows multiple entries per member per meeting)
CREATE TABLE role_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id BIGINT REFERENCES meetings(id) ON DELETE CASCADE,
    member_id BIGINT REFERENCES members(id) ON DELETE CASCADE,
    role_id BIGINT REFERENCES role_catalog(id) ON DELETE CASCADE,
    speech_title TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(meeting_id, member_id, role_id) -- Prevents assigning the same role to the same member twice in one meeting
);

-- 6. Attendance Table
CREATE TABLE attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id BIGINT REFERENCES meetings(id) ON DELETE CASCADE,
    member_id BIGINT REFERENCES members(id) ON DELETE CASCADE,
    status attendance_status DEFAULT 'Present',
    UNIQUE(meeting_id, member_id)
);